### PR TITLE
feat(core): add possibility to use a custom validate function for env validation

### PR DESCRIPTION
**Pull request by LeoAnesi**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features) -> see [here](https://github.com/nestjs/docs.nestjs.com/pull/1534) for the corresponding PR

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Only `joi` validation is possible, which is forcing users to add this lib in addition to `class-validator`  

Issue Number: [318](https://github.com/nestjs/config/issues/318)

## What is the new behavior?

A user can now choose between `class-validator` and `joi` to validate env variables

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
I've spent some time thinking about this feature and I believe that adding 2 additional dependencies and hardcoding even more complexity into this package (which should be mainly responsible for managing configurations) doesn't make too much sense. Perhaps, instead of putting all that INTO the package, we should instead provide a new, additional configuration property (let's say, `validateFn` or just 'validate`) that would allow specifying a validation function. This function could throw an exception (or not) that would prevent the application from bootstrapping. And hence, anyone using this package who wants/prefers using `class-validator` could simply use this validator inside the custom validation function. Such a function would take an object containing all the loaded variables as an argument.

**Comment by LeoAnesi** [comment]
I agree with you, I just updated the code :
- I added deprecation notice on the `validationSchema` and `validationOptions` as I feel like, as you said, there shouldn't be much hardcoded logic in this package, so those should be removed at some point. That said I'm not sure I did it in a correct way, that's actually my first open source contribution, so tell me if I need to change anything 
- I'm currently making the related documentation, should say in it that it is recommended to use validate function or should I add it after JOI ?

**Comment by kamilmysliwiec** [comment]
Last thing: I think we should not be deprecating the `validationSchema` option since less experienced developers (or just anyone who wants to use Joi either way) may find it useful + we would avoid introducing a breaking change

**Comment by LeoAnesi** [comment]
The reasons for me to deprecate `validationSchema` are :
- People that want to use Joi can still use it with `validate` function with a little overhead (they will loose some error formatting)
- Keep a minimal complexity inside this package for maintainability
- On the long run for people using Nest, keep only one way to validate environment variables

Also the breaking change would be for a later release

@kamilmysliwiec if you still don't agree with me I'll remove deprecation notices

**Comment by kamilmysliwiec** [comment]
Although I fully understand your points, I'd love to avoid any breaking changes that lead to unnecessary frustration (developers' frustration), especially when there's a very minimal benefit for the package itself.

**Comment by LeoAnesi** [comment]
@kamilmysliwiec deprecation is removed !

**Comment by kamilmysliwiec** [comment]
Thank you! 💪 This will be added in the next minor release

**Comment by bgolyoo** [comment]
@kamilmysliwiec 

> Thank you! 💪 This will be added in the next minor release

Just curious, about when will that be?

**Comment by kamilmysliwiec** [comment]
This should be added already

**Pull request merged**
