### PR TITLE
feat(yam-config): Testing feature yaml-config

### PR DESCRIPTION
**Pull request by iam-dev**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x ] Other... Please describe:
Documentation and testing yaml config
```

## What is the current behavior?

Not able to read config.yml according yml structure 
Issue Number: N/A

## What is the new behavior?
Ability to read config.yml within yml structure

## Does this PR introduce a breaking change?
```
[ ] Yes
[x ] No
```

## Other information

### CODE REVIEW

**Comment by jmcdo29** [comment]
What's the use case for a `.yml` over `.env` as defined by [dotenv](https://www.npmjs.com/package/dotenv)

**Comment by iam-dev** [comment]
please check our Discord conversations...

**Comment by kamilmysliwiec** [comment]
@iam-dev can you please explain it here? I'm not aware of the reason either.

**Comment by iam-dev** [comment]
I'm creating graphql gateway using nestjs. I was inspired by express gateway, they are using yml for system env and gateway services. Check also. https://github.com/ExpressGateway/express-gateway.

It's easier to maintain our infrastructure using only 1 file. Infrastructure as a code. This solution doesn't change the dotenv support of a Nestjs config.. The key is now more specified by it use for example :admin.port' or 'http.port'

**Comment by kamilmysliwiec** [comment]
Is there any reason why we should hardcode this feature in the library? I believe that using YAML files should be fairly easy to accomplish with custom configuration files https://docs.nestjs.com/techniques/configuration#custom-configuration-files (with less overhead btw). Maybe instead we should just add another section about this in the documentation (on how to use custom configuration files to load YAML files with `js-yaml`)?

**Comment by iam-dev** [comment]
Thanks .. I will remove this from the library and add custom configuration file using yml in test directory and I will also change the docs..

**Comment by kamilmysliwiec** [comment]
If you can create a PR to the docs, that would be awesome!

**Comment by iam-dev** [comment]
> If you can create a PR to the docs, that would be awesome!

Can you agree with this yaml test?

If you are, I will change the docs as tested..

**Comment by kamilmysliwiec** [comment]
I fully appreciate your efforts but I don't really see any reasons why we would have to test an external library within this repo. Thanks for your contribution though!

**Pull request closed without merging**
